spring.application.name=ecommerce-backend

# Database connection (Docker PostgreSQL on port 5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce_db
spring.datasource.username=ecommerce_user
spring.datasource.password=ecommerce_pass

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false